sio2project/sinol-make

src/sinol_make/commands/run/__init__.py
src/sinol_make/util.py

I couldn't find an easier and cleaner way of doing this. One of the advantages is that we have full control over what order and how the `config.yml` is saved.

Function for pretty saving the `config.yml`

---

src/sinol_make/commands/run/__init__.py
src/sinol_make/helpers/compiler.py

MacOS has new version of g++ and gcc compilers. Now the tool will check for their existence, but I wonder if there is a better way of doing this.

Allow only `gcc` in versions 9 and 10 on MacOS

---

src/sinol_make/commands/run/__init__.py
tests/packages/vso/prog/vso1.cpp
tests/packages/vso/prog/vsoingen.cpp

`run` output improvements

---

src/sinol_make/__init__.py
src/sinol_make/commands/inwer/__init__.py
src/sinol_make/commands/run/__init__.py
src/sinol_make/util.py
tests/util.py

`subprocess.Popen` is more flexible than `os.system` and it will make easier to avoid problems such as not escaping spaces.

Move to subprocess

---

README.md
pyproject.toml
src/sinol_make/__init__.py

I found a package for autocompletion, but I'd like you to test it. For me the completion works in about a second, so it feels kinda slow. 
After installing sinol-make you can enable it either by adding `eval "$(register-python-argcomplete sinol-make)"` to your `.bashrc` (or `.zshrc`) or using `activate-global-python-argcomplete` and restarting shell.

Add autocompletion

---

.github/workflows/Arch.yaml
.github/workflows/GithubRunner.yaml
.github/workflows/Ubuntu.yaml
.github/workflows/macOS.yaml
pyproject.toml
src/sinol_make/commands/inwer/__init__.py
src/sinol_make/commands/inwer/inwer_util.py
src/sinol_make/commands/inwer/structs.py
src/sinol_make/commands/run/__init__.py
src/sinol_make/commands/run/structs.py
src/sinol_make/helpers/compile.py
src/sinol_make/helpers/compiler.py
src/sinol_make/helpers/package_util.py
src/sinol_make/helpers/printer.py
src/sinol_make/util.py
tests/test_util.py

There were some problems with types and `importlib.resources` in python 3.7 and 3.8.

Fixes for python 3.7 and 3.8

---

README.md

@tonowak could you test if `pacman -S time` installs `time` in /usr/bin/time correctly? I can't test it on my system at the moment

Change `time` installation steps in README

---

src/sinol_make/helpers/compile.py
tests/helpers/test_cache.py

When a file with code A was compiled, the path to the executable was saved for md5sum of code A. Then after changing file's code to code B and compiling it, the executable's path is the same, but it's compiled with code B. The md5sum for code A is still stored. Then after changing file's code to code A again, `sinol-make` sees that there is a md5sum for code A and returns path to the executable, which is still compiled with code B.
Now, information about md5 sums for a file named `file.cpp` is stored in `.cache/md5sums/file.cpp`, which contains the md5sum of the code and path to the executable. This fixes the above problem, because after compiling the same file again, the previous md5sum is deleted.

Fix compilation caching

---

src/sinol_make/commands/export/__init__.py
src/sinol_make/helpers/compile.py
src/sinol_make/helpers/compiler.py
tests/commands/export/util.py

From today, sio will by default use g++12, c++20 and python3.11

Change c++ standard and default compilers

---

src/sinol_make/commands/run/__init__.py
src/sinol_make/helpers/package_util.py
tests/commands/run/test_integration.py
tests/commands/run/test_unit.py
tests/helpers/test_package_util.py

Now `--solutions` and `--tests` can take absolute path, path to file in `prog`/`in` directory or just name of the file. All of those can be in the glob format.
Closes #71

Change `--solutions` and `--tests` flags behaviour

---

src/sinol_make/__init__.py
src/sinol_make/commands/doc/__init__.py
tests/commands/doc/test_integration.py

Now after running `sinol-make doc` all compilation logs are removed, unless `--logs` flag is set. Closes #139

After running `sinol-make doc` remove log files

---

src/sinol_make/commands/export/__init__.py
tests/commands/export/test_integration.py

In `sinol-make export` the executable permission is added to `xyzingen.sh`, as it is required by sio
Closes #141

`sinol-make export` should add +x to `xyzingen.sh`

---

src/sinol_make/oiejq/__init__.py
src/sinol_make/util.py
tests/commands/export/test_integration.py

Python 3.12 added new argument to `tar.extractall` which specifies how the tar files should be handled. When this arguments is not passed `DeprecationWarning` is shown. To fix this, I added a function that passes this argument if the python version is 3.12. Here are informations about this new argument https://docs.python.org/3/library/tarfile.html#extraction-filters

Add an optional argument to fix deprecated warning in Python 3.12

---

src/sinol_make/util.py

The process which starts `check_version` function will now run as a daemon, so it will exit when the main process ends.
Closes #152

Don't wait for process checking version to exit

---

src/sinol_make/commands/gen/__init__.py
src/sinol_make/commands/inwer/__init__.py
src/sinol_make/commands/run/__init__.py
src/sinol_make/util.py
tests/conftest.py

Now the default value for --cpus flag will be the number of cpus - 1.
Closes #153

Change default number of cpus

---

src/sinol_make/__init__.py
src/sinol_make/commands/gen/__init__.py
tests/commands/gen/test_integration.py

Requested in #154. I added flags `--ins` and `--outs` for generating only inputs/outputs. Also, if for some input file an output file doesn't exist, it is generated.

Allow generating only ins/outs in `gen` command

---

src/sinol_make/commands/gen/__init__.py
src/sinol_make/helpers/cache.py
src/sinol_make/helpers/package_util.py
tests/commands/gen/test_integration.py

If the correct solution is changed, the tests cache should be deleted, so that all output tests are regenerated. This didn't happen previously, this PR fixes that.

Remove tests cache on correct solution change

---

src/sinol_make/commands/gen/gen_util.py
src/sinol_make/commands/inwer/inwer_util.py
src/sinol_make/helpers/compile.py
src/sinol_make/util.py
tests/commands/gen/test_integration.py
tests/commands/inwer/test_integration.py
tests/conftest.py
tests/packages/gen/prog/geningen2.cpp
tests/packages/gen/prog/geningen3.cpp
tests/packages/wer/prog/werinwer5.cpp
tests/packages/wer/prog/werinwer6.cpp

Unfortunately, -fsanitize=address and -fsanitize=undefined doesn't work yet on macOS with ARM.

Add -fsanitize

---

src/sinol_make/commands/run/__init__.py
src/sinol_make/helpers/package_util.py

On sio tests in format abc1a1 belong in the test group 1. This PR should make the script consistent with oioioi when assigning test to groups .

Fix get_group to comply with oioioi standards

---

setup.cfg

This repository [seems to be](https://github.com/sio2project/sinol-make/blob/main/LICENSE) licensed under GPLv3, but the license classifier in setup.py says otherwise, which this PR fixes.

Fix the python package's license classifier

---

src/sinol_make/commands/run/__init__.py
tests/packages/lim/prog/lim2.cpp
tests/packages/ovl/prog/ovl.cpp
tests/packages/vso/prog/vso4.cpp
tests/packages/vso/prog/vso7.cpp

This makes some test solutions run for a given amount of seconds properly under oiejq by running a loop bounded by the number of instructions executed.
On faster computers, which execute more instructions per second, the previous behaviour of looping for an amount of real time caused undesired TLE results, which made some tests fail.

Make the oiejq tests less flaky

---

.github/workflows/Arch.yaml
.github/workflows/GithubRunner.yaml
.github/workflows/Ubuntu.yaml
.github/workflows/macOS.yaml

Previously, only pull requests from a branch of this repository were triggering github action workflows.
Adding `pull_request` to the triggers fixes this.

Fix triggering github actions on pull requests

---

src/sinol_make/util.py
tests/test_util.py

Previously, running `save_config` would result in changing `Przykładowe zadanie` to `"Przyk\u0142adowe zadanie"`.
Apart from that function, `yaml.dump` seems to be used only for writing md5sums/filenames and in tests, so there shouldn't be a problem outside of `save_config`.
Steps to reproduce:
1. Run `sinol-make gen && sinol-make run --apply-suggestions` in the example package from this repo
2. Observe escaped unicode in config.yml

Fix saving configs with unicode characters

---

src/sinol_make/__init__.py
src/sinol_make/commands/export/__init__.py
src/sinol_make/contest_types/default.py
src/sinol_make/util.py

Allow for contest specific features on export.

Extend contest API

---

tests/test_oiejq.py

 Update github-runner tests

---

.github/workflows/Arch.yaml
.github/workflows/GithubRunner.yaml
.github/workflows/Ubuntu.yaml
.github/workflows/macOS.yaml

This is to avoid duplicate runs for PRs opened from a branch in the base repository.
One alternative would be to limit `pull_request` to PRs from outside repositories, which might be desired in the future.

Restrict the 'push' workflow trigger to main

---

src/sinol_make/commands/run/__init__.py
tests/commands/run/test_integration.py

Stricter no outs verification
Fix script crashing on lack of any outputs

Modify missing outputs

---

README.md
setup.cfg
src/sinol_make/__init__.py
src/sinol_make/commands/doc/__init__.py
src/sinol_make/commands/export/__init__.py
src/sinol_make/commands/gen/__init__.py
src/sinol_make/commands/inwer/__init__.py
src/sinol_make/commands/run/__init__.py
src/sinol_make/commands/verify/__init__.py
src/sinol_make/interfaces/BaseCommand.py

Introduces these aliases:
- `sinol-make r` for `sinol-make run`
- `sinol-make g` for `sinol-make gen`
- `sinol-make i` for `sinol-make inwer`
- `sinol-make e` for `sinol-make export`
- `sinol-make d` for `sinol-make doc`
- `sinol-make v` for `sinol-make verify`
- `sm` for `sinol-make`

Aliases for commands

---

.github/workflows/Arch.yaml
.github/workflows/GithubRunner.yaml
.github/workflows/Ubuntu.yaml
.github/workflows/macOS.yaml
setup.cfg

Bumped minimum version to 3.9 (3.8 has reached end-of-life) and changed from 3.12 to 3.13 in tests

Bump Python versions

---

src/sinol_make/__init__.py
src/sinol_make/commands/run/__init__.py
src/sinol_make/sio2jail/__init__.py
src/sinol_make/util.py
tests/conftest.py
tests/test_sio2jail.py

WSL2 (released 2019) is based on a Linux VM. In general its behavior is consistent with any other Linux system running in a VM, so there should be no reason to discriminate WSL under `util.is_linux()`.
In the future, we might want to check for specific features such as perf counters being supported, but that is an orthogonal concern.
I have tested with several people using WSL across relatively modern laptops (Intel 8th gen and up) and in all cases the Intel PMU driver passed through enough perf counters for sio2jail to work.
If we wanted to test support for sio2jail more thoroughly, I suspect the best method might be to actually try running sio2jail or the perf tool.

Use sio2jail on WSL

---

src/sinol_make/commands/export/__init__.py
tests/commands/export/util.py

This is already not done locally by sinol-make, so make the exported makefile.in match the local behaviour.

Don't add extra args to chk/ingen/inwer C/CXXFLAGS in makefile.in

---

src/sinol_make/helpers/oicompare.py
src/sinol_make/task_type/__init__.py
src/sinol_make/util.py
tests/helpers/test_oicompare.py
tests/test_util.py

Add oicompare like comparing

---

src/sinol_make/__init__.py
src/sinol_make/commands/run/__init__.py
src/sinol_make/executors/__init__.py
src/sinol_make/executors/detailed.py
src/sinol_make/executors/sio2jail.py
src/sinol_make/executors/time.py
src/sinol_make/sio2jail/__init__.py
src/sinol_make/sio2jail/perf_test.py
src/sinol_make/structs/status_structs.py
src/sinol_make/util.py
tests/conftest.py
tests/test_sio2jail.py

We currently don't pass enough cmdline arguments to sio2jail self-check,
which makes it fail erroneously on some system configurations.
This change prevents that from happening, by using Sio2jailExecutor to
run the self check.
Notably this change required adding the original cmdline to
ExecutionResult for logging errors later - this feels like a leaky
abstraction, but that class actually already carries the process exit
signal and stderr.
Also improved sio2jail related error messages for better user experience.

Run sio2jail self-check with Sio2jailExecutor

---

example_package/config.yml
src/sinol_make/commands/doc/__init__.py
src/sinol_make/util.py
tests/commands/doc/test_integration.py
tests/packages/luadoc/config.yml
tests/packages/luadoc/doc/doczad.tex
tests/util.py

This is necessary to use some TeX features, such as TikZ's graph drawing library.
As there isn't a reasonable way of detecting the necessity of using lualatex, the --latex-compiler option is now also exposed through config.yml, to make it possible to export the package if the statement only compiles with the right latex compiler.

Allow compiling LaTeX with lualatex

---

example_package/config.yml
src/sinol_make/commands/ingen/__init__.py
tests/commands/gen/test_integration.py
tests/packages/gen/prog/geningen7.cpp

Enhance static file handling and add globbing support in tests

---

src/sinol_make/commands/export/__init__.py
tests/commands/export/test_integration.py

Remove '.e' files from prog directory
