sio2project/sinol-make

.gitignore, README.md, pyproject.toml, src/sinol_make/__init__.py, src/sinol_make/commands/run/__init__.py, src/sinol_make/commands/run/structs.py, src/sinol_make/helpers/compile.py, src/sinol_make/util.py, tests/commands/run/test_integration.py, tests/commands/run/test_unit.py, tests/commands/run/util.py, tests/packages/abc/config.yml, tests/packages/abc/prog/abc.cpp, tests/packages/abc/prog/abc1.cpp, tests/packages/abc/prog/abc2.cpp, tests/packages/abc/prog/abc3.cpp, tests/packages/abc/prog/abc4.cpp, tests/packages/abc/prog/abcingen.cpp, tests/packages/abc/prog/oi.h, tests/util.py
- rename subtasks to sinol_expected_scores
- sinol_expected_scores describes what results should given program have
- if sinol_expected_scores is not found in config, all programs are run on all tests and sinol-make suggests new config with sinol_expected_scores
=> Suggest sinol_expected_scores if none found in config.yml

src/sinol_make/__init__.py
In preparation for release, I added --version flag.
For now the version in `pyproject.toml` is 0.0.1, but I think we should release this as 1.0.0
=> Add version flag

pyproject.toml, src/sinol_make/__init__.py
Package `pkg_resources` is deprecated. I found another way of having current version in one place.
=> Remove deprecated package `pkg_resources`

src/sinol_make/__init__.py
=> Bump version for release

src/sinol_make/commands/run/__init__.py, tests/commands/run/test_integration.py, tests/fixtures.py, tests/packages/vso/config.yml, tests/packages/vso/prog/vso.cpp, tests/packages/vso/prog/vso1.cpp, tests/packages/vso/prog/vso2.cpp, tests/packages/vso/prog/vso3.cpp, tests/packages/vso/prog/vso4.cpp, tests/packages/vso/prog/vso5.cpp, tests/packages/vso/prog/vso6.cpp, tests/packages/vso/prog/vso7.cpp, tests/packages/vso/prog/vsoingen.cpp, tests/util.py
Before the status for group was the first not OK status received from executing solutions on individual tests. Now the group will have status based on this priority: TLE, MLE, RTE, WA, OK.
=> Fix execution status order

src/sinol_make/commands/run/__init__.py
=> Redirect solutions' stderr to `/dev/null`

src/sinol_make/commands/run/__init__.py, tests/commands/run/test_integration.py, tests/commands/run/test_unit.py, tests/commands/run/util.py
=> Add flag to exit on failed compilation

README.md, src/sinol_make/commands/run/__init__.py
I got rid of bash `timeout` and replaced it with `subprocess`' timeout, because it was causing some problems. I also fixed killing processes when they run longer then the hard time limit
=> Fix errors with executing solutions

README.md, pyproject.toml, src/sinol_make/__init__.py, src/sinol_make/commands/inwer/__init__.py, src/sinol_make/commands/run/__init__.py, src/sinol_make/helpers/compiler.py, src/sinol_make/helpers/parsers.py, tests/commands/run/test_integration.py
I also added shorter flags for some commands, let me know what you think
=> Change flags to be more Linux-style

src/sinol_make/__init__.py, src/sinol_make/commands/run/__init__.py, tests/packages/chk/prog/chkchk.cpp
I thought that the only allowed first line of checker output is "OK" or "WRONG", but it actually is "OK" for a correct answer and anything else for incorrect.
=> Fix checking of checker output

src/sinol_make/__init__.py, src/sinol_make/commands/run/__init__.py, src/sinol_make/helpers/package_util.py, src/sinol_make/util.py, tests/commands/run/test_integration.py, tests/helpers/test_package_util.py, tests/packages/lim/config.yml, tests/packages/lim/prog/lim.cpp, tests/packages/lim/prog/lim1.cpp, tests/packages/lim/prog/lim2.cpp, tests/packages/lim/prog/lim3.cpp, tests/packages/lim/prog/lim4.cpp, tests/packages/lim/prog/limingen.cpp, tests/util.py
I kinda forgot that not all tests have to have the same time and memory limits. This PR fixes that.
=> Fix running with `time_limits` and `memory_limits` present in config

README.md
Oops, I forgot to update README in #63
=> Update README with `gen` command information

src/sinol_make/__init__.py
=> Print message on `sinol-make` crash

.gitignore, src/sinol_make/__init__.py, src/sinol_make/commands/export/__init__.py, src/sinol_make/commands/inwer/__init__.py, src/sinol_make/commands/run/__init__.py, src/sinol_make/helpers/compile.py, src/sinol_make/helpers/package_util.py, src/sinol_make/helpers/paths.py, src/sinol_make/oiejq/__init__.py, src/sinol_make/util.py, tests/commands/run/test_unit.py, tests/conftest.py, tests/packages/gen/prog/geningen.sh, tests/util.py
I also added code for moving `cache` to `.cache` after updating to a newer version
=> Rename `cache` directory to `.cache`

src/sinol_make/__init__.py, src/sinol_make/helpers/printer.py
For some reason on some terminals the previous code failed. Now this should be fixed
=> Fix problem with `printer.py`

src/sinol_make/commands/gen/gen_util.py, tests/commands/gen/test_integration.py
=> Fix `gen` command changing modification date of shell ingen

tests/commands/run/test_integration.py
Yesterday I didn't have time to add tests for caching bug fix (#135)
=> Add test for caching bug

src/sinol_make/commands/run/__init__.py, tests/commands/run/test_unit.py
=> Fix error `PENDING not in list`

src/sinol_make/commands/export/__init__.py
If there is a latex statement, by compiling it on export we ensure it's has no errors and will correctly compile on oioioi
If there is no latex statement and there is no pdf file, give warning to ensure this is intended (as it's uncommon to export package without a valid statement)
=> Compile statement on export

src/sinol_make/commands/export/__init__.py, src/sinol_make/commands/run/__init__.py, src/sinol_make/contest_types/__init__.py, src/sinol_make/helpers/compile.py, src/sinol_make/helpers/package_util.py
Move config loading and surround it with error checking for parsing yml
Improve ``print_compile_log``
Fix #183
=> Move config loading to package_util

src/sinol_make/commands/doc/__init__.py, src/sinol_make/commands/export/__init__.py, src/sinol_make/commands/gen/__init__.py, src/sinol_make/commands/ingen/__init__.py, src/sinol_make/commands/inwer/__init__.py, src/sinol_make/commands/outgen/__init__.py, src/sinol_make/commands/run/__init__.py, src/sinol_make/contest_types/default.py, src/sinol_make/contest_types/oi.py, src/sinol_make/util.py, tests/commands/export/test_unit.py
Make ocen creating based on a flag
=> Add contest specific arguments

.github/workflows/Arch.yaml, .github/workflows/Ubuntu.yaml, src/sinol_make/commands/init/__init__.py, tests/commands/init/test_integration.py, tests/commands/init/test_unit.py, tests/fixtures.py
Create task from the given template in github repo.
Update all the places with task id to provided id
=> Init command

src/sinol_make/__init__.py
Add sleep to increase visibility of information about new versions.
Comply with PEP 8: E501 and PEP 8: E722
=> Better indicate availability of new version.

src/sinol_make/__init__.py, src/sinol_make/commands/run/__init__.py, tests/commands/run/test_integration.py
=> Remove tests cache after adding/removing checker

src/sinol_make/commands/ingen/ingen_util.py, src/sinol_make/commands/inwer/__init__.py, src/sinol_make/commands/inwer/inwer_util.py, src/sinol_make/helpers/compile.py, tests/commands/inwer/test_unit.py, tests/packages/gen/prog/geningen5.cpp, tests/packages/wer/prog/werinwer.cpp
Update inwer compilation to work the same as ingen compilation.
Add flags to allow to distinguish ingen, inwer and other programs. 
As this is not supported on oioioi, this feature is not added for checker compilation. (Ingen and inwer may be removed from the final package)
=> Ingen inwer compilation

src/sinol_make/__init__.py, src/sinol_make/helpers/compiler.py, src/sinol_make/helpers/func_cache.py, src/sinol_make/helpers/package_util.py, src/sinol_make/helpers/parsers.py, src/sinol_make/util.py, tests/helpers/test_package_util.py, tests/util.py
Caching results of checking default compilers decreased duration of `sinol-make -v` by a second
=> Performance improvements

src/sinol_make/commands/ingen/__init__.py, src/sinol_make/commands/outgen/__init__.py, src/sinol_make/helpers/package_util.py, tests/commands/gen/test_unit.py
=> Validate tests in parallel

example_package/config.yml, src/sinol_make/__init__.py, src/sinol_make/commands/ingen/__init__.py, src/sinol_make/util.py, tests/commands/gen/test_integration.py
=> Ingen deleting handwritten tests

.github/workflows/Arch.yaml, .github/workflows/GithubRunner.yaml, .github/workflows/Ubuntu.yaml, .github/workflows/macOS.yaml
=> Bump python versions in tests

src/sinol_make/helpers/compiler.py
=> Update gcc compilers on macos

src/sinol_make/executors/sio2jail.py
=> Fix bug with reporting memory limit exceeded
